Algoritmo "semnome"
// Disciplina  : Algoritmos e lógica de programação
// Professor   : Erinaldo
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Vinícius Colombo
// Data atual  : 8/16/2024
Var
// Seção de Declarações das variáveis 

   x,y:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   escreva("Digite dois números: ")
   leia(x)
   leia(y)
   
   escreva("Sua soma é: ",x+y)
   
Fimalgoritmo
