Algoritmo "semnome"
// Disciplina: Algoritmos e lógica de programação
// Professor: Erinaldo 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 8/21/2024
Var
// Seção de Declarações das variáveis 
   i,j:inteiro

Inicio

   para i de 1 ate 10 faca
        para j de 1 ate 10 faca
        escreva(j ," x", i, " =", i*j)
        fimpara
        escreval
   fimpara

Fimalgoritmo